In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse','poisson'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.306463,0.087752,0.012501,0.011693,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",0.843684,0.755099,0.852291,0.815405,0.834709,0.820237,0.034794,16
1,2.182281,0.161317,0.065631,0.018224,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.852041,0.766832,0.860669,0.823954,0.837288,0.828157,0.033134,9
2,0.246316,0.021355,0.018752,0.015309,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.829871,0.763436,0.839312,0.816604,0.827066,0.815258,0.026903,22
3,1.601711,0.096789,0.068756,0.032175,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.854990,0.777727,0.862879,0.830119,0.836596,0.832462,0.029837,5
4,0.196680,0.007920,0.034379,0.022966,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.854644,0.773409,0.844259,0.811387,0.833002,0.823340,0.028799,13
5,1.618486,0.046466,0.071880,0.007654,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.855848,0.778250,0.860069,0.832130,0.840094,0.833278,0.029336,1
6,0.976171,0.053966,0.009378,0.007657,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",0.813961,0.748107,0.840914,0.816703,0.821550,0.808247,0.031512,24
7,8.581013,0.145255,0.054892,0.022910,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.840170,0.762480,0.855062,0.822942,0.842464,0.824624,0.032714,11
8,0.595088,0.037212,0.003126,0.006252,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.839173,0.774345,0.845266,0.816484,0.823702,0.819794,0.024965,17
9,6.067247,0.632355,0.096972,0.072807,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.857577,0.780391,0.857874,0.824923,0.844547,0.833063,0.028945,2
10,0.637760,0.069827,0.026218,0.029619,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.849063,0.751933,0.854915,0.814780,0.836797,0.821497,0.037403,14
11,5.444839,0.377818,0.075006,0.026883,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855341,0.775219,0.854858,0.829521,0.845571,0.832102,0.029939,8
12,0.368862,0.032110,0.012501,0.011692,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.831107,0.760378,0.862574,0.810995,0.822352,0.817481,0.033303,19
13,2.244627,0.093133,0.056253,0.021195,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.844248,0.766907,0.854468,0.819784,0.834668,0.824015,0.030755,12
14,0.184128,0.024813,0.025002,0.021196,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.830000,0.768314,0.853027,0.825564,0.826413,0.820664,0.028043,15
15,1.584550,0.067796,0.063307,0.030930,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.857388,0.778136,0.860662,0.826994,0.837404,0.832117,0.029738,7
16,0.221947,0.025066,0.025000,0.025388,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.842534,0.750790,0.838573,0.815273,0.833170,0.816068,0.033945,20
17,1.586963,0.090015,0.053131,0.018751,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.854886,0.776829,0.860511,0.828504,0.842084,0.832563,0.029976,4
18,0.366339,0.037674,0.025003,0.018751,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",0.843310,0.749209,0.850370,0.797852,0.831622,0.814473,0.037282,23
19,2.502037,0.086829,0.063648,0.022003,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.848950,0.771087,0.852622,0.817321,0.841527,0.826302,0.030222,10
20,0.254145,0.008252,0.009376,0.007655,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.846039,0.758796,0.846103,0.815504,0.831065,0.819501,0.032394,18
21,1.789726,0.038323,0.068757,0.021195,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.855490,0.776657,0.861592,0.828953,0.842313,0.833001,0.030334,3
22,0.245340,0.029603,0.007248,0.009016,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.844451,0.757527,0.829451,0.821051,0.824630,0.815422,0.030026,21
23,1.791079,0.179807,0.060244,0.019169,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858683,0.777907,0.857815,0.827251,0.840403,0.832412,0.029654,6

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
Children_input=float(input("Children:"))
sex_male_input=int(input("sex male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))

Age: 19
BMI: 27.900
Children: 0
sex male 0 or 1: 0
smoker yes 0 or 1: 1

In [14]:
future_prediction=grid.predict([[age_input,bmi_input,Children_input,sex_male_input,smoker_yes_input]])
print("future_prediction={}".format(future_prediction))

future_prediction=[17468.151045]

C:\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(